apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: payment-watchdog-ui
  namespace: lexure-mvp

resources:
- service-account.yaml
- configmap.yaml
- secret.yaml
- service.yaml
- deployment.yaml

commonLabels:
  app: payment-watchdog
  component: ui
  version: v1.0.0

images:
- name: payment-watchdog-ui
  newTag: latest
