apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres-deployment.yaml
  - postgres-service.yaml
  - postgres-pv.yaml
  - postgres-secrets.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: payment-watchdog
      environment: development
    includeSelectors: true
    includeTemplates: true
