apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lexure

resources:
  - deployment.yaml
  - service.yaml
  - service-account.yaml
  - configmap.yaml
  - secret.yaml

labels:
  - pairs:
      app.kubernetes.io/name: payment-watchdog
      app.kubernetes.io/component: backend
      app.kubernetes.io/part-of: payment-watchdog
      environment: development
    includeSelectors: true
    includeTemplates: true

images:
  - name: payment-watchdog
    newName: payment-watchdog
    newTag: latest
