apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-watchdog
  labels:
    app.kubernetes.io/name: payment-watchdog
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: payment-watchdog
