apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../components/postgres
  - ../components/redis
  - ../components/ingress
  - ../components/monitoring
  - ../../apps/payment-watchdog-mvp
  - ../../apps/recovery-orchestration

commonLabels:
  app.kubernetes.io/part-of: payment-watchdog
  environment: development
