apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-monitor.yaml

# Add the Prometheus Operator CRDs as a dependency
configurations:
  - kustomizeconfig.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: payment-watchdog
      environment: development
    includeSelectors: true
    includeTemplates: true
