apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lexure-mvp

resources:
  - namespace.yaml
  - storage-class.yaml
  - components/postgres
  - components/redis
  - components/ingress

labels:
  - pairs:
      app.kubernetes.io/part-of: payment-watchdog
      environment: development
    includeSelectors: true
    includeTemplates: true
